[tool.poetry]
name = "labfisica"
version = "0.1.0"
description = "Herramientas de Python para laboratorios de fÃ­sica"

[tool.poetry.dependencies]
python = "^3.8"
matplotlib = "^3.5.0"
pandas = "^1.4.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
